### ISSUE TITLE
Error about Duplicate File Load in 10.2.7.54577

### ISSUE THREAD

**Issue by jonespm** [nulian/Outfitter#1]
Error from latest WoW

```
Message: Interface/AddOns/Outfitter/Outfitter.toc:47 Duplicate File Load Detected. [Interface/AddOns/Outfitter/OutfitterStrings_ru.lua] first loaded at [Interface/AddOns/Outfitter/Outfitter.toc:46]
Time: Tue May  7 17:41:05 2024
Count: 2
```

Looks like that is duplicated and it hasn't complained about it before. Thanks for addon!

https://github.com/nulian/Outfitter/blob/99b7688e268a165afb070be93f2468e5e69a748f/Outfitter.toc#L46

**Comment by nulian** [comment]
Is fixed
