### ISSUE TITLE
Lua error when logging in 

### ISSUE THREAD

**Issue by b-morgan** [nulian/Outfitter#3]
The following error occurs when logging into WoW 11.0.0 (build 55939) using Outfitter 11.0.4:

2x bad argument #1 to '?' (Usage: local locations = C_EquipmentSet.GetItemLocations(equipmentSetID))
[string "=[C]"]: in function `GetItemLocations'
[string "@Outfitter/OutfitterOutfits.lua"]:770: in function `GetItems'
[string "@Outfitter/OutfitterEquipment.lua"]:976: in function `RestoreSavedStack'
[string "@Outfitter/OutfitterEquipment.lua"]:961: in function `Initialize'
[string "@Outfitter/Outfitter.lua"]:4761: in function `Function'
[string "@Outfitter/Libraries/MC2SchedulerLib/MC2SchedulerLib.lua"]:242: in function `OnUpdate2'
[string "@Outfitter/Libraries/MC2SchedulerLib/MC2SchedulerLib.lua"]:178: in function `OnUpdate'
[string "@Outfitter/Libraries/MC2SchedulerLib/MC2SchedulerLib.lua"]:20: in function <...fitter/Libraries/MC2SchedulerLib/MC2SchedulerLib.lua:20>

Locals:
(*temporary) = "bad argument #1 to '?' (Usage: local locations = C_EquipmentSet.GetItemLocations(equipmentSetID))"

**Comment by nulian** [comment]
Could I maybe get the Outfitter.lua file from the character you have the issue with. Because it seems you have some invalid data inside the config and with this information not sure how to solve it.

**Comment by nulian** [comment]
I will probably release a small change tomorrow that checks that input for valid values.
Got some issue at publishing a new version at curse.

It's in the last commit on this repo.

**Comment by b-morgan** [comment]
Installed Outfitter 11.0.5 and tested with two characters, one success and one failure. The character specific Outfitter.lua for the failing character is included below.

[Outfitter.zip](https://github.com/user-attachments/files/16516056/Outfitter.zip)

**Comment by b-morgan** [comment]
I added the 11.0.6 change to OutfitterOutfits.lua and the error on login went away.
